### ISSUE TITLE
adminGentelella theme sidebar bugged

### ISSUE THREAD

**Issue by renlok** [renlok/WeBid#341]
The dropdowns on the sidebar open but close instantly making it almost impossible to use
only tested with chrome so far

**Comment by aucsta** [comment]
I had this problem but if you press it again it opens. this was doing my head in so I downloaded the theme from the webid main site and altered the header page and then uploaded it with the css and js files and now it works like a dream ill upload my files because they are working then you cn do as you will with them

**Comment by aucsta** [comment]
can this issue be closed now

**Comment by Aucsta** [comment]
this theme needs serious attention as nothing works since it was updated
